baseURL = "/"
languageCode = "en-us"
title = "Sand Point Homeowner's Association"
enableRobotsTXT = "true"
paginate = "3"
disableKinds = ["RSS"]
[permalinks]
  page = "/:filename/"
[taxonomies]
  tag = "tags"
  member = "members"