baseURL = "vibrant-villani-4c13f8.netlify.com"
languageCode = "en-us"
title = "Sand Point CC Homeowner's Association"
enableRobotsTXT = "true"
paginate = "3"
disableKinds = ["RSS"]
[taxonomies]
  tag = "tags"
