backend:   
  name: git-gateway   
  branch: master

media_folder: "/static/images/"
public_folder: "/images/"

collections:
- name: "news" # Used in routes, e.g., /admin/collections/blog
  label: "News Post" # Used in the UI
  editor:
    preview: false
  folder: "/content/news" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", required: false, widget: "datetime"}
    - {label: "Draft", name: "draft", required: false, widget: "boolean", default: true}
    - {label: "Categories (all lowercase, separate with a comma)", name: "tags", required: false, widget: "list"}
    - {label: "Featured Image", name: "featuredImage", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}
